# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "466d1063c75d0584538920e0e227cab5"
name = "subscription-manager"
application_url = "https://subscription-manager-5ask.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_own_subscription_contracts,read_price_rules,read_products,write_customers,write_discounts,write_own_subscription_contracts,write_price_rules,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://subscription-manager-5ask.onrender.com/auth/callback",
  "https://subscription-manager-5ask.onrender.com/auth/shopify/callback",
  "https://subscription-manager-5ask.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://socoba-bundles-subscription.onrender.com/portal"
subpath = "subscription-manager"
prefix = "apps"
