# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b168c1a4cd97fcd089199c7c7a835ce"
name = "subscription-manager"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_purchase_options,write_products,write_purchase_options"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
