api_version = "2025-04"

# 1. THE BUTTON
[[extensions]]
name = "socoba-account-widget"
handle = "socoba-account-widget"

uid = "728196b1-c31d-41ee-e52d-c5e1a7cb6ffc2cb2459c"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
api_access = true

# 2. THE FULL PAGE
[[extensions]]
name = "socoba-subscription-portal"
handle = "socoba-subscription-portal"

uid = "775aef5f-04d8-a74c-39e1-cf31c2b0e3a31d9f5e7c"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/SubscriptionPage.jsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true